---
name: CI-Automation
permissions: {}

on:
  push:
    branches:
      - feat/automation
  workflow_dispatch:

jobs:
  call-windows-build:
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/ci-windows.yml
    with:
      publish_release: 'false'
      release_commit: ${{ github.sha }}
      release_version: automation-dev
